dns-zone: use ${Dns_Source}; output formatting with dnsEcho()

diff --git a/sbin/dns-zone b/sbin/dns-zone
--- a/sbin/dns-zone
+++ b/sbin/dns-zone
@@ -4,19 +4,17 @@
 
 # 20190408, joseph.tingiris@gmail.com
 
+Dns_Dir=$(dirname $(dirname "$(readlink -e "$0")"))
+Dns_Source="${Dns_Dir}/bin/dns"
+if [ ! -r "${Dns_Source}" ]; then
+    printf "\naborting, '${Dns_Source}' source file not readable\n\n"
+    exit 2
+fi
+source "${Dns_Source}"
+
 #
 # global variables
 #
-
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-
-if [ ${#Verbose} -eq 0 ]; then
-    declare -i Verbose=4 # WARNING
-else
-    if [ ${#VERBOSE} -gt 0 ]; then
-        Verbose=${VERBOSE}
-    fi
-fi
 
 Verbose_Level_Prefix=on
 
@@ -35,13 +33,6 @@ Dns_View_Valid=1
 #
 # functions
 #
-
-# output an 'aborting' message and exit with a non-zero return code
-function aborting() {
-    local abort_message="${@}"
-    printf "\naborting, %s\n\n" "${abort_message}"
-    exit 2
-}
 
 function usage() {
     printf "\nusage: %s <action> <zone name> [view name]\n\n" "${0}"
@@ -83,31 +74,6 @@ function usage() {
     exit 1
 }
 
-if [ "$(type -t verbose)" != "function" ]; then
-    function verbose() {
-        local verbose_arguments=($@)
-        local verbose_level verbose_message
-
-        if [ ${#2} -gt 0 ]; then
-            verbose_message=(${verbose_arguments[@]}) # preserve verbose_arguments
-            verbose_level=${verbose_message[${#verbose_message[@]}-1]}
-        else
-            verbose_message="${1}"
-            verbose_level=""
-        fi
-
-        if [[ ! ${verbose_level} =~ ^[0-9]+$ ]]; then
-            verbose_level=0
-        fi
-
-        if [[ ${Verbose} =~ ^[0-9]+$ ]]; then
-            if [ ${verbose_level} -le ${Verbose} ]; then
-                (>&2 printf "%b\n" "${verbose_message}")
-            fi
-        fi
-    }
-fi
-
 # Main
 
 Warnings=()
@@ -125,22 +91,6 @@ if [ ${#1} -eq 0 ] || [ ${#2} -eq 0 ]; then
 fi
 
 #
-# validate Dns_Dir
-#
-
-Dns_Dir=$(egrep "[[:space:]]directory[[:space:]]" /etc/named.conf | awk '{print $NF}' | sed -e '/"/s///g' -e '/;/s///g' -e '/\/$/s///g')
-
-if [ ! -d "${Dns_Dir}/zone" ]; then
-    aborting "ERROR: ${Dns_Dir}/zone directory not found"
-fi
-
-verbose "NOTICE: Dns_Dir= ${Dns_Dir}"
-
-if [ ! -f "${Dns_Dir}/etc/named.primary.conf" ]; then
-    aborting "ERROR: ${Dns_Dir}/etc/named.primary.conf file not found"
-fi
-
-#
 # validate action
 #
 
@@ -150,11 +100,13 @@ for Dns_Action in ${Dns_Actions[@]}; do
         break
     fi
 done
+
 if [ ${Dns_Action_Valid} -eq 0 ]; then
     shift
 else
     usage "invalid action '${1}'"
 fi
+
 verbose "INFO: Dns_Action=${Dns_Action}"
 
 #
@@ -168,6 +120,7 @@ if [ ${#Zone} -gt 0 ]; then
 else
     usage "invalid zone '${1}'"
 fi
+
 if [[ "${Zone}" =~ rpz$ ]]; then
     Origin="${Zone}"
     Soa=localhost
@@ -209,6 +162,7 @@ else
         fi
     fi
 fi
+
 verbose "INFO: Dns_View=${Dns_View}"
 
 #
@@ -326,7 +280,7 @@ if [ "${Zone}" == "dns.conf" ]; then
             printf "Zone = ${Zone},"
             printf " Action = ${Dns_Action},"
             printf " View = ${View}"
-            printf "\n"
+            printf "\n\n"
 
             $0 "${Dns_Action}" "${Zone}" "${Zone_View}"
             if [ $? -ne 0 ]; then
@@ -365,7 +319,7 @@ for Server in ${Servers[@]}; do
         printf " View = ${View},"
         printf " Origin = ${Origin},"
         printf " Soa = ${Soa}"
-        printf "\n"
+        printf "\n\n"
 
         #
         # process primary & secondary zone configs
@@ -382,8 +336,6 @@ for Server in ${Servers[@]}; do
             if [ "${Dns_Action}" != "check" ]; then
                 continue
             fi
-        else
-            printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} template zones config" "${Template_Zones_Conf}"
         fi
 
         if [ -f "${Zones_Conf}" ]; then
@@ -394,8 +346,6 @@ for Server in ${Servers[@]}; do
                 fi
             fi
 
-            printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone config" "${Zones_Conf}"
-
             if grep "^[[:space:]]*zone[[:space:]]\"${Zone}\"" "${Zones_Conf}" &> /dev/null; then
                 Zones_Conf_Exists=0 # true
             else
@@ -404,9 +354,15 @@ for Server in ${Servers[@]}; do
         fi
 
         if [ ${Zones_Conf_Exists} -eq 0 ]; then
-            printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone config" "OK"
+            [ "${Dns_Action}" != "delete" ] && dnsEcho "[EXISTS]:[${Server}][${View}]=(${Zone}) ${Zones_Conf}"
+
+            if [ "${Dns_Action}" == "add" ] || [ "${Dns_Action}" == "delete" ] || [ "${Dns_Action}" == "force" ]; then
+                if dnsBackup "${Zones_Conf}"; then
+                    dnsEcho "[BACKUP]:[${Server}][${View}]=(${Zone}) ${Zones_Conf}"
+                fi
+            fi
         else
-            printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone config" "NOT FOUND"
+            [ "${Dns_Action}" != "add" ] && dnsEcho "[NOT FOUND]:[${Server}][${View}]=(${Zone}) ${Zones_Conf}"
         fi
 
         if [ "${Dns_Action}" == "delete" ] || [ "${Dns_Action}" == "force" ]; then
@@ -421,7 +377,7 @@ for Server in ${Servers[@]}; do
                 [ $Add_Rc -eq 0 ] && sed -i -e '1{/^$/d}' -e '${/^$/d}' "${Zones_Conf}"
                 Add_Rc=$?
                 if [ $Add_Rc -eq 0 ]; then
-                    printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone config" "DELETED"
+                    dnsEcho "[REMOVE]:[${Server}][${View}]=(${Zone}) ${Zones_Conf}"
                     Zones_Conf_Exists=1
                 else
                     aborting "failed to remove '${Zone}' from ${Zones_Conf}"
@@ -431,6 +387,8 @@ for Server in ${Servers[@]}; do
 
         if [ "${Dns_Action}" == "add" ] || [ "${Dns_Action}" == "force" ]; then
             if [ ${Zones_Conf_Exists} -eq 1 ]; then
+                dnsEcho "[TEMPLATE]:[${Server}][${View}]=(${Zone}) ${Template_Zones_Conf}"
+
                 Add_Rc=0
                 [ $Add_Rc -eq 0 ] && echo >> "${Zones_Conf}"
                 Add_Rc=$?
@@ -443,14 +401,12 @@ for Server in ${Servers[@]}; do
                 [ $Add_Rc -eq 0 ] && sed -i -e '1{/^$/d}' -e '${/^$/d}' "${Zones_Conf}"
                 Add_Rc=$?
                 if [ $Add_Rc -eq 0 ]; then
-                    printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone config" "ADDED"
+                    dnsEcho "[ADD]:[${Server}][${View}]=(${Zone}) ${Zones_Conf}"
                     Zones_Conf_Exists=0
                 else
                     aborting "failed to add '${Zone}' to ${Zones_Conf}"
                 fi
             fi
-        else
-            printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone config" "NOT ADDED"
         fi
 
 
@@ -471,8 +427,6 @@ for Server in ${Servers[@]}; do
                 if [ "${Dns_Action}" != "check" ]; then
                     continue
                 fi
-            else
-                printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} template zone file" "${Template_Zone_File}"
             fi
 
             if [ -f "${Zone_File}" ] && [ ! -w "${Zone_File}" ]; then
@@ -482,7 +436,6 @@ for Server in ${Servers[@]}; do
                 fi
             else
                 if [ -s "${Zone_File}" ]; then
-                    printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone file" "${Zone_File}"
                     Zone_File_Exists=0 # true
                 else
                     Zone_File_Exists=1 # false
@@ -490,32 +443,38 @@ for Server in ${Servers[@]}; do
             fi
 
             if [ ${Zone_File_Exists} -eq 0 ]; then
-                printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone file" "OK"
+                [ "${Dns_Action}" != "delete" ] && dnsEcho "[EXISTS]:[${Server}][${View}]=(${Zone}) ${Zone_File}"
+
+                if [ "${Dns_Action}" == "add" ] || [ "${Dns_Action}" == "delete" ] || [ "${Dns_Action}" == "force" ]; then
+                    if dnsBackup "${Zone_File}"; then
+                        dnsEcho "[BACKUP]:[${Server}][${View}]=(${Zone}) ${Zone_File}"
+                    fi
+                fi
             else
-                printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone file" "NOT FOUND"
+                [ "${Dns_Action}" != "add" ] && dnsEcho "[NOT FOUND]:[${Server}][${View}]=(${Zone}) ${Zone_File}"
             fi
 
             if [ "${Dns_Action}" == "delete" ] || [ "${Dns_Action}" == "force" ]; then
                 if [ $Zone_File_Exists -eq 0 ]; then
                     rm -f "${Zone_File}"
                     if [ $? -eq 0 ]; then
-                        printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone file" "REMOVED"
+                        dnsEcho "[REMOVE]:[${Server}][${View}]=(${Zone}) ${Zone_File}"
                         Zone_File_Exists=1
                     else
                         aborting "failed to remove '${Zone_File}'"
                     fi
-                else
-                    printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone file" "NOT REMOVED"
                 fi
             fi
 
             if [ "${Dns_Action}" == "add" ] || [ "${Dns_Action}" == "force" ]; then
                 if [ ${Zone_File_Exists} -eq 1 ]; then
+                    dnsEcho "[TEMPLATE]:[${Server}][${View}]=(${Zone}) ${Template_Zone_File}"
+
                     Add_Rc=0
                     [ $Add_Rc -eq 0 ] && sed -e "s#++ORIGIN++#${Origin}#g" -e "s#++SERIAL++#${Serial}#g" -e "s#++SOA++#${Soa}#g" -e "s#++VIEW++#${View}#g" -e "s#++ZONE++#${Zone}#g" -e "s#++ZONE_DIR++#${Zone_Dir}#g" "${Template_Zone_File}" >> "${Zone_File}"
                     Add_Rc=$?
                     if [ $Add_Rc -eq 0 ]; then
-                        printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} zone file" "CREATED"
+                        dnsEcho "[CREATE]:[${Server}][${View}]=(${Zone}) ${Zone_File}"
                         Zone_File_Exists=0
                     else
                         aborting "failed to create '${Zone_File}"
@@ -560,7 +519,6 @@ for Server in ${Servers[@]}; do
             fi
 
             if [ -f "${Response_Policy_Conf}" ]; then
-                printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} response policy" "${Response_Policy_Conf}"
                 if grep "^[[:space:]]*zone[[:space:]]\"${Zone}\"" "${Response_Policy_Conf}" &> /dev/null; then
                     Response_Policy_Conf_Exists=0 # true
                 else
@@ -568,19 +526,25 @@ for Server in ${Servers[@]}; do
                 fi
             fi
 
+            if [ $Response_Policy_Conf_Exists -eq 0 ]; then
+                [ "${Dns_Action}" != "delete" ] && dnsEcho "[EXISTS]:[${Server}][${View}]=(${Zone}) ${Response_Policy_Conf}"
+
+                if [ "${Dns_Action}" == "add" ] || [ "${Dns_Action}" == "delete" ] || [ "${Dns_Action}" == "force" ]; then
+                    if dnsBackup "${Response_Policy_Conf}"; then
+                        dnsEcho "[BACKUP]:[${Server}][${View}]=(${Zone}) ${Response_Policy_Conf}"
+                    fi
+                fi
+            else
+                [ "${Dns_Action}" != "add" ] && dnsEcho "[NOT FOUND]:[${Server}][${View}]=(${Zone}) ${Response_Policy_Conf}"
+            fi
+
             if [ ! -f "${Response_Policy_Conf}" ] && [ $Response_Policy_Conf_Exists -eq 1 ]; then
                 printf "response-policy {\nzone \"${Zone}\";\n};" > "${Response_Policy_Conf}"
                 if [ $? -eq 0 ]; then
-                    printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} response policy" "CREATED"
+                    dnsEcho "[CREATE]:[${Server}][${View}]=(${Zone}) ${Response_Policy_Conf}"
                 else
                     aborting "failed to create '${Response_Policy_Conf}'"
                 fi
-            fi
-
-            if [ $Response_Policy_Conf_Exists -eq 0 ]; then
-                printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} response policy" "FOUND"
-            else
-                printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} response policy" "NOT FOUND"
             fi
 
             if [ "${Dns_Action}" == "delete" ] || [ "${Dns_Action}" == "force" ]; then
@@ -595,13 +559,11 @@ for Server in ${Servers[@]}; do
                     [ $Add_Rc -eq 0 ] && sed -i -e '1{/^$/d}' -e '${/^$/d}' "${Response_Policy_Conf}"
                     Add_Rc=$?
                     if [ $Add_Rc -eq 0 ]; then
-                        printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} response policy" "DELETED"
+                        dnsEcho "[REMOVE]:[${Server}][${View}]=(${Zone}) ${Response_Policy_Conf}"
                         Response_Policy_Conf_Exists=1
                     else
                         aborting "failed to remove '${Zone}' from ${Response_Policy_Conf}"
                     fi
-                else
-                    printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} response policy" "NOT DELETED"
                 fi
             fi
 
@@ -616,13 +578,11 @@ for Server in ${Servers[@]}; do
                     [ $Add_Rc -eq 0 ] && sed -i -e '1{/^$/d}' -e '${/^$/d}' "${Response_Policy_Conf}"
                     Add_Rc=$?
                     if [ $Add_Rc -eq 0 ]; then
-                        printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} response policy" "ADDED"
+                        dnsEcho "[ADD]:[${Server}][${View}]=(${Zone}) ${Response_Policy_Conf}"
                         Response_Policy_Conf_Exists=0 # true
                     else
                         aborting "failed to add '${Zone}' to ${Zones_Conf}"
                     fi
-                else
-                    printf "%-${Printf_Pad}b = %s\n" "'${Zone}' ${Server} ${View} response policy" "NOT ADDED"
                 fi
             fi
 
@@ -636,22 +596,21 @@ for Server in ${Servers[@]}; do
 
         fi
 
-    done
 
+        #
+        # named-checkconf, once, for every primary record
+        #
 
-    #
-    # named-checkconf, once, for every primary record
-    #
-
-    if [ "${Server}" == "primary" ]; then
-        Zone_Status=$(named-checkconf -z 2> /dev/null | grep "${Zone}\/" 2> /dev/null)
-        printf "%-${Printf_Pad}b = " "'${Zone}' ${Server} ${View} zone status"
-        if [ ${#Zone_Status} -eq 0 ]; then
-            echo "NOT LOADED"
-        else
-            echo ${Zone_Status}
+        if [ "${Server}" == "primary" ]; then
+            Zone_Status=$(named-checkzone "${Zone}" "${Zone_File}" 2> /dev/null | tr '\n' ' ')
+            if [ ${#Zone_Status} -eq 0 ] || [ "${Zone_Status}" == "" ] || [ ! -r "${Zone_File}" ]; then
+                dnsEcho "[STATUS]:[${Server}][${View}]=(${Zone}) NOT LOADED"
+            else
+                dnsEcho "[STATUS]:[${Server}][${View}]=(${Zone}) ${Zone_Status}"
+            fi
         fi
-    fi
+
+    done
 
 done
 
